### ISSUE TITLE
Should CWT and UCCS have different COSE header parameters?

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#159]
I don't think this has been discussed (but I might be wrong).

The draft currently specifies:

```
   +-----------+-------+----------------+------------------------------+
   | Name      | Label | Value Type     | Description                  |
   +===========+=======+================+==============================+
   | cwt       |  TBD1 | COSE_Messages  | A CBOR Web Token (CWT) or an |
   |           |       | / map          | Unprotected CWT Claims Set   |
   +-----------+-------+----------------+------------------------------+
```

Alternative would be to define two different 'cwt' and 'uccs' COSE header parameters

**Comment by emanjon** [comment]
While there are similar in one way, they have very different security properties and use cases. I think a have a slight preference to standardize two parameters.

**Comment by marco-tiloca-sics** [comment]
I also tend to prefer two distinct parameters. That would also simplify the initial parsing of credentials, since a dedicated COSE header parameter (rather than the type of the CBOR item) tells you the exact credential format.

This applies also beyond EDHOC, in case these formats are generally used to upload/distribute public keys, e.g. in the ACE Group Manager for Group OSCORE [1]. In that particular case, the same exact format has to be used by all the members of a same group for their public keys. Thus, having two distinct parameters "cwt" and "uccs" prevents possible ambiguity/misunderstanding to handle if there is only one parameter meaning "cwt or uccs".

[1] https://datatracker.ietf.org/doc/draft-ietf-ace-key-groupcomm-oscore/
