### ISSUE TITLE
Possible collision of credential identifiers after credential transport by value

### ISSUE THREAD

**Issue by marco-tiloca-sics** [lake-wg/edhoc#165]
Think of this scenario. An Initiator C1 offers its (self-generated) UCCS credential by value in ID_CRED_I with inner 'kid'=42, and EDHOC completes correctly by accepting the UCCS as Trust On First Use (TOFU). Later on, a different Initiator C2 also offers to the same Responder its (self-generated) UCCS credential by value in ID_CRED_I with inner 'kid'=42 again, and EDHOC completes correctly, again by accepting the UCCS as TOFU. You can think of the same scenario applied to two Responders' credential transported by value in ID_CRED_R just as well.

It's probably up to a peer's policies --- possibly reflected in the applicability statement for servers --- to determine whether it is fine or not to accept a UCCS/CWT credential that has a 'kid' equal to another credential already stored.

If the policy allows to accept multiple credentials with the same 'kid', later on in the following executions of EDHOC those will likely be referred by their 'kid' in ID_CRED_X, and something needs to be adapted in the EDHOC engine. That is, failing to verify an EDHOC message with one of those peer credential must not discontinue the protocol and send an Error Message right away. Instead, the next credential with that 'kid' should be tried. Only if the message processing fails with all of those credentials, an Error Message is sent.

**Comment by emanjon** [comment]
Thanks Marco,

I think this is a general problem not really related to CTW or UCSS by value. It exists as long as
more that one entity determines the kid values. I also think it is not really an EDHOC problem. For
identification of cryptogrphic keys EDHOC relies purely on COSE by using COSE header maps.

COSE writes:

      Applications MUST NOT assume
      that 'kid' values are unique.  There may be more than one key with
      the same 'kid' value, so all of the keys associated with this
      'kid' may need to be checked.

https://datatracker.ietf.org/doc/html/draft-ietf-cose-rfc8152bis-struct-15

I don't know if there is need for more guidance from a COSE perspective.


In EDHOC the following sentence should maybe be reformulated.

   It is RECOMMENDED that ID_CRED_x uniquely identify the public
   authentication key as the recipient may otherwise have to try several
   keys.

Might be good to remind readers that applications MUST NOT assume that 'kid' values are unique

**Comment by marco-tiloca-sics** [comment]
Looks good to me, thanks! Just a small typo and editorial fix:

s/as unique as possible to as the/as unique as possible, since the
