### ISSUE TITLE
Optional message_4 for key confirmation

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#18]
The Initiator does not get explicit key confirmation until the Initiator has received a MAC calculated with a key derived from PRK_4x3m and TH_4. One way to get explicit key confirmation is that R sends a OSCORE request or response to I.

Should EDHOC specify an optional message_4 with the sole purpose to give I explicit key confirmation (Suggestion from Karl Norrman which did a formal verification of EDHOC). The fourth message could be very short and simple

   message_4 = (
     ? C_I : bstr_identifier,
     CIPHERTEXT_4
   )

where CIPHERTEXT_4 is only a MAC, i.e. length of plaintext == 0

**Comment by gselander** [comment]
The Initiator can still send OSCORE messages directly after message_3 has been sent. 

Note that a fourth message might have other benefits than purely cryptographic as discussed previously on the list, e.g., to avoid issues where message_3 is lost or delayed due to unreliable transport. 
 
Also note it is proposed that message_3 may as an option be sent in an OSCORE request, see draft-palombini-core-oscore-edhoc

**Comment by marco-tiloca-sics** [comment]
I think it's good to define Message 4. If defined, I suppose optionality is about sending it, while it has to be supported and understood as for the other messages.

I agree these have the advantages beyond security mentioned above.

Since it's optional, one can wonder for how long the Initiator should possibly wait for it before giving up, and possibly start sending application data anyway if it does not care of key confirmation before doing that.

How about this kind of signaling?

1) In Message 2, the Responder can signal that it will send Message 4 later on, as a heads up to the Initiator.

2) In Message 3, the Initiator can:

2a) Explicitly request for Message 4 to be sent, if its sending was not anticipated with the signaling in Message 2 (see above); or

2b) If an upcoming Message 4 was signaled in Message 2 (see above), explicitly tell the Responder to not send Message 4, as not caring to achieve key confirmation before sending application data.

**Comment by TimothyClaeys** [comment]
I am also in favor of defining a `message 4` which can be optionally requested by the Initiator. 

I don't know if it is useful to provide the capability to the Responder to notify the Initiator in `message 2` that it will send a `message 4`. I am unsure about the advantage of letting the Responder decide to send a` message 4` if the Initiator didn't specifically request it.

Personally, I think it makes more sense to append the option to `message 1`, next to the other negotiation parameters, but there might be advantages to attaching the request to `message 3` that I don't know.

**Comment by eduingles** [comment]
I don't have strong opposition to adding an optional message 4, but I do not see it necessary. 

Since this WG is looking for an authentication protocol with OSCORE, I opt for solutions such as [draft-palombini-core-oscore-edhoc](https://tools.ietf.org/html/draft-palombini-core-oscore-edhoc-01) instead of including more messages.

I do not see any practical scenario where that fourth message is really necessary and it is not solved by the following OSCORE message. If there is, I'd love to see it.

On the other hand, adding the fourth message implies adding complexity to the process, increasing the packet size and increasing the interaction time. This increases the chances of an error and the need to repeat the authentication process. Therefore, I prefer to avoid giving the option.

Nevertheless, it is interesting to analyze the cost of adding an additional message in networks such as LoRaWAN where an error can be a huge punishment.

Having said that, I understand that we are talking about something optional but giving that option could lead to it being widely used in scenarios where it is not necessary and decrease the performance of the protocol.

**Comment by emanjon** [comment]
Sending message_3 in OSCORE as specified in draft-palombini-core-oscore-edhoc and requiring a response seems to solve all problems for use cases when The EDHOC Initiator is the OSCORE Client.

What about cases when the EDHOC Initiator is the OSCORE Server?

**Comment by gselander** [comment]
The case with OSCORE Server being EDHOC Initiator seems less problematic. No actions takes place before the first OSCORE request arrives to the server, and the OSCORE processing hands over the plain text message for CoAP processing only after having verified the MAC and thereby obtained key confirmation.

**Comment by emanjon** [comment]
I don't think the problem is not OSCORE processing before the Initiator has gotten "delivery receipt for message_3  / key confirmation". The Initiator can e.g. start sending as many OSCORE request as it wants without knowing for sure that the Responder has received and accepted message_3.

The only problem as I see it is the the Initator has sent message_3 and then does not receive any OSCORE from the Responder. How long does the Initiator store the keying material? If the Initiator is only a CoAP server it cannot send a OSCORE request to the Responder.


The case with OSCORE Server being EDHOC Initiator seems less problematic. No actions takes place before the first OSCORE request arrives to the server, and the OSCORE processing hands over the plain text message for CoAP processing only after having verified the MAC and thereby obtained key confirmation.

**Comment by gselander** [comment]
I have not seen any objection to specify message_4 in response to message_3 so we should do that. We should make it optional to implement so it does not add complexity when not needed. 

Attempted processing description:
* message_4 must only be sent if signalled by the Initiator. 
* It is optional for the Initiator to signal message_4. 
* If the Responder receives the signal for message_4 and does not support sending of message_4 then it MUST send an error message back and the protocol MUST be discontinued. 
* If the Responder receives the signal for message_4 and supports sending of message_4 then it is RECOMMENDED to send message_4.
* If the Initiator requests message_4 and does not receive it, the Responder should be prepared that the Initiator may discontinue the protocol or discard the keys. 

We need to define the signal for message_4, most likely in message_3, whose integrity can be immediately verified.

**Comment by emanjon** [comment]
I have now added specification of an optional to support message_4 to master. The EDHOC message_4 should be seen as replacement for an protected application leyer message from R to I. The intention is that it is only used when no  protected application leyer messages are sent from R to I.

At the last interim it was discussed to signal the need for key confirmation in message_1 or message_3. But when starting to implement this I wonder if that is the right thing to do. message_4 is only needed in some rare cases where no applicaiton data is sent or when application data is only sent in the I to R direction.

As this message_4 is a rare case it might be easier to just mandate key confirmation. Key confirmation is achieved by all deployments that send application data from R to I. Might be easier to mandate message_4 for the rare cases when no application data is sent from R to I. Then nothing changes in current implementations.

Are there any uses cases that do not need key confirmation. I would say no, and even if there is I do not think they are common enough to introduce signaling in message_1 or 3

**Comment by gselander** [comment]
I agree with the proposal. But how does the Responder know at reception of message_3 that it will later send an application message to the initiator? In case the responder is CoAP server, it requires a request to provide key confirmation in the response, and it does not a priori know if it will recieve an request with protected application data. With draft-palombini-core-oscore-edhoc it will, but this is optional to use.

**Comment by gselander** [comment]
Do we to define transport of application data/auxiliary data in message_4?

**Comment by marco-tiloca-sics** [comment]
The Responder would probably have to follow an application policy to decide if it has to send Message_4 or not.

However, strictly while processing Message_3, the Responder may not really know why it is running EDHOC, i.e. for what exact applications. This means that a Responder running multiple applications that rely on EDHOC would need to have a single common policy covering all of them, as to whether to send Message_4 or not.

An alternative would be to decide based on the particular identity keys used while running EDHOC. Then different applications (requiring key-confirmation or not) can be associated to different identity keys, and taking a decision about sending Message_4 becomes easy. The price to pay is having multiple identity keys, although just two might suffice.

**Comment by gselander** [comment]
No unified view from the discussion at Hackathon. 

Example of comments:
* An explicit signal is useful
* Handle out of band, e.g. using applicability statement and transport layer messages.

**Comment by highlunder** [comment]
I'm late to the discussion, so maybe I'm missing something. To me, having a well defined option for AD_4-data seems useful for all cases where AD_3-data is used in message3 to piggy-back a request where the initiator expects a reply with content.

If not, how are those scenarios meant to be handled?

**Comment by gselander** [comment]
Included in -06 and earlier versions.
