### ISSUE TITLE
Test Vectors - more suits

### ISSUE THREAD

**Issue by stoprocent** [lake-wg/edhoc#185]
Hi Guys

I needed to generate test vectors for more suits ... in particular suit 2 and 3 and I have switched libsodium in my fork to mbedtls but use generic PSA crypto interface API: https://github.com/stoprocent/edhoc/tree/feature/mbedtls/test-vectors-11

Test vectors generator code in the current format isn't the most cutting edge :) I would be happy to contribute here to improve it but would you consider changing c++ to something like python, nodejs or swift maybe?

Libsodium as crypto backend does not have support for all required suits. mbedtls (which I have used) with PSA has an interface to define such calls but has no implementation to support EdDSA. 

Also, JSON and Text handling in the current generator add tons of boilerplate code that makes the generator more complicated.

I would be nice to narrow down language and crypto lib that covers all the required cipher suits and removes JSON/TXT and CBOR boilerplate code.

In the meantime If someone have a time and will to have a look here https://github.com/stoprocent/edhoc/tree/feature/mbedtls/test-vectors-11 it would be nice.

**Comment by gselander** [comment]
The authors proposed in LAKE interim Dec 15 that -traces should include 4 traces:
1.
> method 3 (stat-stat)
> suite 0 (X25519)
> I CCS
> R CCS
> ID_CRED_I kid
> ID_CRED_R kid 

2.
> method 0 (sig-sig)
> suite 0 (X25519) suite 2 (ECDSA) 
> I Cert X.509
> R Cert X.509
> ID_CRED_I x5t
> ID_CRED_R x5t

3.
> wrong selected cipher suite (ERR-CODE 2)
> method 1 (sig-stat)
> suite 1 (EdDSA, X25519)
> I Cert X.509
> R CCS
> ID_CRED_I x5t
> ID_CRED_R kid

4.
> method 2 (stat-sig)
> suite 3 (P-256, ECDSA)
> I Cert X.509
> R CCS
> ID_CRED_I x5chain
> ID_CRED_R kccs

**Comment by gselander** [comment]
Marco previously (can't find the reference) proposed 4 traces, but only using methods 0 and 3, and each with cipher suites 0 and 2. Arguments in favor:
 * Then there would be traces for all methods with recommended suites 
      * Mixed methods are easy to check given details of un-mixed (sig-sig/ stat-stat)
      * Difference between cipher suites 0 and 1 (2 and 3) are too small to merit separate trace

**Comment by emanjon** [comment]
```
Marco previously (can't find the reference) proposed 4 traces, but only using methods 0 and 3, and each with cipher suites 0 and 2. Arguments in favor:

    Then there would be traces for all methods with recommended suites
        Mixed methods are easy to check given details of un-mixed (sig-sig/ stat-stat)
        Difference between cipher suites 0 and 1 (2 and 3) are too small to merit separate trace

```

Why was this worth mentioning? I agree with Marco about the methods. But this just seems like an argument that 2 methods and 2 cipher suites would be acceptable, not that it would better or preferred. If we are making 4 traces, making 4 methods and 4 cipher suites is trivial....

**Comment by emanjon** [comment]
I think 1 and 3 should definitely be in the traces. They should probably be recommended for transports that can handle 53 byte payloads without significant performance degradation.

**Comment by marco-tiloca-sics** [comment]
Here's the references [1][2].

From [2]: "Compromise between TC and JM. I see appropriate to have both methods 0 and 3 for both ciphersuites 0 and 2."

[1] https://mailarchive.ietf.org/arch/msg/lake/0N2-CzE-hRQjXNZfUw8edDHZhto/
[2] https://datatracker.ietf.org/meeting/112/materials/minutes-112-lake-01.md

**Comment by stoprocent** [comment]
Hi Guys 

I have a crazy end of the year in terms of the amount of work. We had a few rounds of revisions of test vectors. We have fixed some tiny problems like double CBOR bstr in `CRED` when X509 is used. We are working with `Stefan Hristozov` with `uEDHOC` and the vectors we have seems to be complete. The main set we work with is exactly like you have specified in the 4th trace. The upcoming week will be a little bit better so I will send you our final set.

**Comment by gselander** [comment]
@stoprocent Thx for the update!

**Comment by gselander** [comment]
About what methods and suites in -traces. I understand the argument provided by @marco-tiloca-sics as follows:

EDHOC presents two different kinds of authentication, signatures or static DH, and recommends (since Jan 2020 although this is currently discussed) two different curves, ECDSA or EdDSA. In order to test any recommended implementation there is a need to be able to verify against one of the four combinations (SIG, STAT) x (ECDSA, EdDSA). 

The proposal presented at the LAKE interim (see above) allows this, assuming you can test against another implementation supporting the other side of the test vector in the mixed cases. However, if this is not the case and we want to enable any recommended implementation to be tested against itself, then we should support ECDSA and EdDSA for both SIG-only (method 3) and STAT-only (method 0), which I believe is Marco's proposal.

@TimothyClaeys You proposed 8 traces in the LAKE interim. If you were to select 4 would you go for Marco's proposal or the proposal at the LAKE interim?

(As a minor variant suite 0 could be replaced by suite 1, and suite 2 by suite 3. This is independent of the above choice of method x curve.)

**Comment by emanjon** [comment]
Marco's comments are old. There are also I lot of other old comments. The current proposal took all these into account. A lot of the comments during the past meetings seemed to confuse traces (which is aimed to increse understanding for a human reader) to the test vectors in JSON which are intended to actually test an implementation.

I see no reason to bring up any of the old comments. If people have comments on the current proposal that would be good, but such comments should also motivation why the change increases understanding for a human reader and why the large number of test vectors in JSON format would not be enough.

**Comment by emanjon** [comment]
[1] https://mailarchive.ietf.org/arch/msg/lake/0N2-CzE-hRQjXNZfUw8edDHZhto/
[2] https://datatracker.ietf.org/meeting/112/materials/minutes-112-lake-01.md
Provides no motivation whatsover. 

Instead of @gselander speculating maybe @marco-tiloca-sics can expand on why he would like these changes and how they would inprove the traces document compared to current suggestion.

Note that there has been several people requesting all four methods.... Right now I think the next step will be to just change the SIG-SIG trace to ECDSA and have a real X509 certificate. It seems like everybody agrees that this is an improvement. I think the traces document will stay at 2 traces until there is consensus on how to expand the number of traces. Right now there seems to not be consensus on how to proceed. Göran has promised to do 2 traces, and has stated can consider 4 if that makes people significantly more happy. I think more than 4 is not relalistic given the work it would require.

- Independently, the 13 X25519 JSON test vectors should be merged with equally many P-256 test vectors. An Table of contents should be added. These JSON test vectors are meant for verifying implementations. The traces document is just a small documented subset of the JSON test vectors for a human reader providing a bridge between the spec and the JSON test vectors.

**Comment by marco-tiloca-sics** [comment]
Just like Göran phrased it above, I can imagine someone implementing only ciphersuite 0 (or only ciphersuite 2) and hoping to have annotated walkthrough traces for both SIG-SIG and Stat-Stat for conveniently self-testing with that ciphsersuite.

Limited to ciphersuite 0, that was the case until EDHOC v -08, where the traces still in the EDHOC draft covered methods 0 and 3. At that time, I could imagine as a natural follow-up having two equivalent traces for ciphersuite 2, still without excluding the possible addition or further traces.

I can surely live without the above and I understand the intent of not having too many traces in a draft. If the idea is to add only 2 new ones, I agree that the additions presented at the latest LAKE interim are preferable as bringing more added value, while the JSON test vectors are still meant for the main verification process.
