### ISSUE TITLE
Length of labels, removal of master

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#204]
RFC 8446 states:
   "Note: With common hash functions, any label longer than 12 characters
   requires an additional iteration of the hash function to compute.
   The labels in this specification have all been chosen to fit within
   this limit."

12 is specific for TLS, but even if the number is slighty higher for EDHOC the following labels might currently require an extra iteration.

   Label: OSCORE_Master_Secret
   Label: OSCORE_Master_Salt

I would suggest we calculate the exact length for EDHOC. Add that length as a consideration in the draft. And shorted down any long labels to not be longer.

**Comment by emanjon** [comment]
```
  info = (
     transcript_hash : bstr,		32 bytes
     label : tstr,					x bytes
     context : bstr,				1 bytes
     length : uint,				1-2 bytes
   )
HKDF padding  1 byte
HMAC padding 9 bytes

For short lengths the label can be 20 bytes
For long lengths the label can be 19 bytes

We need to shorten:
OSCORE_Master_Secret
OSCORE_Master_Salt

I suggest removing "Master". I future update of OSCORE might rename the key to Main secret. But we will never be able to update the label.

Suggestion:
We need to shorten:
OSCORE_Secret
OSCORE_Salt



35
long 36

19-20 bytes label
```

**Comment by emanjon** [comment]
I think removal of master is it's own issue. While we can update the terminology in an update, the labels are frozen and cannot be changed.

**Comment by chrysn** [comment]
Appreciated, as these are strings lugged around in every firmware update.

**Comment by gselander** [comment]
Closing since #205 is merged.

**Comment by chrysn** [comment]
Updating my implementation, I noticed that these are in a CBOR structure anyway (and not concatenated into strings).

So as these are all registered, why not go all the way and make them integers?

**Comment by gselander** [comment]
label : tstr

What do you want to make integers?

**Comment by malishav** [comment]
That makes sense to me

**Comment by gselander** [comment]
Right, we could use something else instead of unique text strings. The current construct is:

EDHOC-Exporter(label, context, length) = EDHOC-KDF(PRK_4x3m, TH_4, label, context, length)

If not label, then context (bstr) can be unique for this use of PRK_4x3m and TH_4. Is the proposal to register unique byte strings, or to change the definition of the function?

**Comment by gselander** [comment]
Reopening this issue, since there is new input.

**Comment by chrysn** [comment]
The proposal is to replace all inputs that ever go into the "label" argument -- anything else would be adding complexity.

For a concrete proposal, we would change

```
  label : tstr,
```

to

```
  label : uint,
```

and define, in order of occurrence in the document:

```cddl
LABEL_MAC_2 = 0
LABEL_KEYSTREAM_2 = 1
LABEL_MAC_3 = 2
LABEL_K_3 = 3
LABEL_IV_3 = 4
```

with all occurrences of `"MAC_2"` with `LABEL_MAC_2` etc.

The exporter registry would then grow a n int field, and look like this:

```
Value: 0
Label: EDHOC_K_4
Description: Key used to protect EDHOC message_4
Reference: [[this document]]

Value: 1
Label: EDHOC_IV_4
Description: IV used to protect EDHOC message_4
Reference: [[this document]]

Value: 2
Label: OSCORE_Master_Secret
Description: Derived OSCORE Master Secret
Reference: [[this document]]

Value: 3
Label: OSCORE_Master_Salt
Description: Derived OSCORE Master Salt
Reference: [[this document]]
```

(It doesn't matter here that there is overlap in the values -- just as it was never ruled out that "K_3" could become a label in the string based EDHOC Exporter Label Registry. That has and still is OK because it's used with different PRKs and transcript hashes. At any rate it's good that all these stay under 23 even with some room for other users, so implementers can store things preencoded if they so desire.)

As for the security analyses, the numbers have the same properties as the strings -- they are self-delimited, and relative uniqueness properties should be the same no matter whether it's strings or numbers (at least when dealing in absolutes; if someone picked an unregistered number at random they're more likely to pick an assigned one than with strings, but that was already "maybe broken"). Length of input is reduced, but that is part of the point, and removing the "_Master" was fine already.

**Comment by marco-tiloca-sics** [comment]
Based also on further discussions with @chrysn 

* If the change is made to have integer labels, this should happen to all the labels involved. That is, not only to the labels provided as input to EDHOC-Exporter(), but also to the labels "KEYSTREAM_2" etc. that are a direct input to EDHOC-KDF(). This avoids having an implementation of EDHOC-KDF() to handle both types as possible input.

* The labels to actually register should still be only those intended as input to EDHOC-Exporter(), i.e., there is no need to register integer labels that are a direct input to EDHOC-KDF() (corresponding to the current "KEYSTREAM_2" etc.). In fact, same integer values would not be a problem in practice, since PRK_4x3m clearly points to the exporter labels when used as first argument in EDHOC-KDF().

* What can be useful is to make clear, as much as now for the tstr version, that potential labels defined in the future as part of EDHOC extensions and to directly use with EDHOC-KDF() have to be different from those already defined in that space, i.e., "KEYSTREAM_2" etc.

**Comment by emanjon** [comment]
- Changing label to integers seems fine with me.

- I don't see why the Label below would stay in the specification. This would just be a variable name in the implementation, or?

- I assume that there is no benefit with int here as the uint is not sent on the wire. 0-255 would be stored as a single byte in the program and then converted to cbor when used.

**Comment by emanjon** [comment]
Note that somebody suggested that this is good to to as late as possible just to break compability.

**Comment by emanjon** [comment]
Based on the input from the formal verification, we will likely have 3 more internal EDHOC labels. Likley something like the following:

Derived from PRK_2e
------------------------------
LABEL_KEYSTREAM_2
LABEL_SALT_2e

Derived from PRK_3e2m
------------------------------
LABEL_MAC_2
LABEL_K_3
LABEL_IV_3
LABEL_SALT_3e2m

Derived from PRK_3m
------------------------------
LABEL_MAC_3
LABEL_PRK_OUT

**Comment by gselander** [comment]
Resolve in PR #286. Close this when that is merged.
