### ISSUE TITLE
Change MTI cipher suite to (0 AND 1) OR (2 AND 3)

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#209]
Separate issue from Stefan's review #194:

"Constrained endpoints SHOULD implement cipher suite 0 or cipher suite 2."

The difference between 0 and 1 and between 2 and 3 is only the size of the tag, i.e. the used algorithms are the same. -> I will suggest changing to "...suite 0/1 or cipher suite 2/3" or similar.

**Comment by gselander** [comment]
Relates to #22. I think this is a good idea.

**Comment by gselander** [comment]
A proposal in PR #200

**Comment by emanjon** [comment]
This makes sense to me

**Comment by malishav** [comment]
I propose we merge this once we converge on #22

**Comment by emanjon** [comment]
#22 and #209 are very independant.

I think 1 and 3 should probably be recommended for transports that can handle 53 byte payloads without significant performance degradation.

**Comment by emanjon** [comment]
There was discussion during the meeting regarding endpoint / device. The current draft use both as a well as implementation. I think device is useful when we talk about "constrained devices" but not otherwise. The endpoint does in general not need to be a "device". It might be software in the cloud or some chip where EDHOC is used on the internal bus.
