### ISSUE TITLE
Use of SHA-512 in constrained IoT.

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#21]
SHA-512 is not supported on many IoT devices and the question is if it ever will. Currently SHA-256 have wide support and is often HW accelerated. Adding also SHA-512 requires more code storage. If SHA-256 gets replaces it would likely be with SHAKE128 or some future XOF emerging from the NIST lightweight standardization protect (e.g. Gimli).

Ed25519 is currently only specified with SHA-512. While there are benefits of having a single algorithm, CFRG should maybe have taken IoT more into consideration. Specifying Ed25519 with another hash algorithm is technically easy, but would mean even less implementations.

It has been suggested that draft-ietf-lwig-curve-representations-05 and W-25519 from Draft NIST SP 800-186 would solve this problem. As far as we know, they only helps with implementing X25519 and Ed25519 on devices which only has acceleration of Weierstrass curves. They do not affect the hash function in any way. We plan to add references to draft-ietf-lwig-curve-representations-05 and W-25519 with the text that they may help with HW acceleration.

Is the use of SHA-512 in Ed25519 a problem?

**Comment by gselander** [comment]
Ed25519 has several benefits, including performance, which makes it very well suited for a constrained setting, but supporting multiple hash functions is an issue. The bundling of Ed25519 and SHA-512 makes the threshold for changing to Ed25519 high. Bundling Ed25519 with another even less common secure hash function does not make this easier.

Either we accept that constrained devices will for a long time to come (also considering life time of the device) not be able to make use of the widely accepted upcoming signature algorithm, or we need to make the transition easier. 

It has been discussed before, but perhaps we have now better arguments for the case of Ed25519 with SHA-256? Although it is far from ideal to specify multiple variants, the difference between Ed25519/SHA-512 and Ed25519/SHA-256 is very small. The implementation effort for extending support from the first to the second is small, and the change is only needed in those servers that communicates with constrained devices. Supporting the two SHA algorithms is no issue on the non-constrained side.

Shall we ask CFRG to specify Ed25519 with SHA-256?

**Comment by gselander** [comment]
Copying from Ilari's recent email to LWIG/COSE:

"And some notes about making version of Ed25519 that uses SHA-256:

- The Ed25519 subkey derivation needs to be split into two hashes
  instead of running once and splitting the result. The input fits into
  one block anyway, so it will still be fast. For example,
  a=SHA256(0|k_priv) and seed=SHA256(1|k_priv).
- It is not trivially possible to replace the inner hash SHA512(seed|M)
  with SHA256(seed|M). However, it turns out that the order in fact
  does allow this replacement.
- If one wants noisy signatures, one way is to replace SHA256(seed|M)
  with SHA256(seed|M)^noise. The noise must be independent of the
  private key and seed, but otherwise bad noise (including completely
  broken one) will not cause immediate catastrophic failure.
- If one wants randomized signatures, due to the same reasons as why
  the inner hash may be replaced, it is recommended to generate more
  randomness than 256 bits, and then use SHA256 to squash it to 256
  bits. This hedges against not-quite-ideal random number generators
  that would otherwise cause catastrophic failure. However, it will
  not prevent broken random number generator from causing immediate
  catastrophic failure.
- The outer hash SHA512(R|A|M) can trivially be replaced by
  SHA256(R|A|M)."

The mail also has some details about qDSA:
https://mailarchive.ietf.org/arch/msg/cose/3WATdZGKvprM7qCZ_axVccvfYzU/

**Comment by pbtgit** [comment]
It would be good to have metrics comparing SHA-512 in terms of code size, message size and computations:
To my knowledge SHA-512 can be accelerated using NEON extension of ARM. Message size is still highly relevant though.

**Comment by eduingles** [comment]
My concern is with the constrained devices that are close to the minimum requirements for running EDHOC. I would not switch to SHA-512 at this time without the support of the manufacturers. Using alternatives that are not HW accelerated I believe would considerably reduce the use of EDHOC on those devices. Even nrf52840 does not support SHA-512 by hardware either although it supports Ed25519 (https://infocenter.nordicsemi.com/pdf/nRF52840_PS_v1.1.pdf). Therefore, I am in favour of keeping SHA-256 if this implies that the devices can take advantage of the hardware modules and avoid doing it by software.

On the other hand, in line with #22 , I would pose the same question. What kind of devices should be supported in EDHOC?

**Comment by gselander** [comment]
SHA-256-only implementations are supported as of 70088cc.
