### ISSUE TITLE
Mandatory to implement cipher suite

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#22]
Considering the potential long deployment times for these device it seemed prudent to require a cipher suite based on Curve25519 (cipher suite no. 0).

EdDSA (and to a smaller degree X25519) does not have as many IoT implementations as ES256 and P-256, but draft-ietf-lwig-curve-representations-05 and W-25519 is suggested to provide a work-around for implementing X25519 and Ed25519 on devices which only has acceleration of Weierstrass curves.

Still remain the issues with SHA-512 (see #21) and with supporting multiple SHA algorithms (#2).

Options:

1. Change MTI cipher suite to one based on ECDSA, e.g., no. 2. This has negative consequences on performance and security, which will remain for long time.

2. Keep MTI cipher suite 0. This may mean accept that some devices will not implement MTI cipher suite. This is beyond the control of the specification and has a number of issues.

3. Define a MTI cipher suite using Curve25519 which has the potential to be widely implemented, e.g., based on a TBD Ed25519 with SHA-256 (see #21). This requires a specification, but would be possible to implement with legacy Weierstrass curve computations and hash algorithm.

**Comment by marco-tiloca-sics** [comment]
I tend to prefer Option 2 as to what is MTI. The uncertainty on deploying Option 3 might be even larger than for Option 2.

The Group OSCORE document [1] also indicates Ed25519 as MTI. The outcome of this discussion will likely affect Group OSCORE, as better to have the same MTI signature algorithm of EDHOC. Thinking of devices that use EDHOC and OSCORE on one hand, and Group OSCORE on the other hand, having a single signature algorithm implemented would be clearly preferable if not unavoidable.

Just for information, see the nRF52840 DK [2] equipped with the CryptoCell CC310 accelerator [3] and providing HW acceleration for Ed25519.


[1] https://datatracker.ietf.org/doc/draft-ietf-core-oscore-groupcomm/

[2] https://www.nordicsemi.com/-/media/Software-and-other-downloads/Product-Briefs/nRF52840-DK-product-brief.pdf?la=en&hash=5D78D8104D4FC04D539BDBACFBB5150F34487447

[3] https://infocenter.nordicsemi.com/index.jsp?topic=%2Fps_nrf9160%2Fcryptocell.html

**Comment by TimothyClaeys** [comment]
I tend to prefer option 3. I think option 1 is not preferable because of the long term impact it would have. 

Concerning the deployment issues of option 3, one aspect we can consider is that upcoming devices (like the nRF52840) will have all the hardware building blocks to fully accelerate Ed25519 with SHA256. The ARM cryptocell has hardware acceleration for SHA-2, but only up to 256 [1]. I am not aware of old or new constrained devices with hardware acceleration for SHA-512.

[1]: [https://developer.arm.com/ip-products/security-ip/cryptocell-300-family](https://developer.arm.com/ip-products/security-ip/cryptocell-300-family)

**Comment by chrysn** [comment]
The documentation of the cryptocell (eg. [in the nrf52840 docs](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcomp_matrix_nrf52840%2FCOMP%2Fnrf52840%2FnRF52840_doc_ref_design_files_overview.html)) is confusing to me. It states that it has acceleration for SHA up to 256, and that it supports Ed25519 (and the document it cites for it is the original Ed25519 one that puts SHA-512 in the example).

Has anyone outside the hardware builders specified Ed25519 with SHA-256 anywhere so far? If so, option 3 might be a lot faster in that it could be as simple as allocating COSE identifiers for that specified algorithm combination, but it'd at least need a specification.

---

From the point of view of implementing this in anything but the most constrained devices, going with 3 would make things a bit harder: Support for Ed25519 as in [RFC8032](https://tools.ietf.org/html/rfc8032) is widely available, but for the 256 version not so, and even if right now someone would produce a published RFC about Ed25519-SHA256 *and* people like the OpenSSL maintainers started adding it, it'd still take considerable time to be available on widespread systems. Having an existing specification out there, even if it's as short as an application note, may help getting a head start there as it could justify starting work on the additions in the widespread libraries.

**Comment by eduingles** [comment]
I am aware of the security issues and would like to support option 2. However, I must go for option 1. Forcing cipher suites with Ed25519 would make it difficult to use EDHOC on Cortex M3 like devices. For example, Openmote B and Zolertia Firefly with the CC2538 microchip can run P-256 in hardware while the studies of Ed25519 on Cortex M3 devices mention issues in its execution. 

I consider that denying the use of P-256 establishes an important red line that would leave many devices out. Also, the arguments here should be consistent with issue #21 on SHA-512. And since it would mark the future of the protocol, I would raise a question. Will EDHOC be an IoT protocol designed for constrained devices with P-256 or EDHOC will be for not so constrained devices?

**Comment by gselander** [comment]
First of all, it is acknowledged that it may be an issue to support Ed25519 and this the reason why we have the discussion about whether MTI algorithms really are mandatory to implement in constrained devices, which definitely are the target for EDHOC.

Second, one reason for ECC based on Curve25519 is superiour performance, which should be good news for constrained IoT.

Third, if Curve25519 based crypto is not available then those devices will have to settle for P-256, or for mapping Curve25519 to Weierstrass coordinates (draft-ietf-lwig-curve-representations). The specification needs to provide guidance here. But we don't want to prevent moving to what is expected to be better and more performant algorithms.

@eduingles Could you please provide a reference to issues of using Ed25519? Assuming Ed25519 is specified with SHA-256 (opion 3), does that help or what additional/remaining issues do you see?

**Comment by chrysn** [comment]
If it turns out that both the specified curves have flaws that implementors may consider insurmountable for their deployments, and that option 3 is harder than just putting an entry in the registry pointing to whoever already specified it,

would it be an option to, rather than making one MTI, state that there are currently no suitable algorithms to make MTI, and instead it is recommended that implementations provide both 1 and 2 if they can (otherwise, either of them) until a universally suitable curve is specified (which is then invited to update this document to make it MTI)?

**Comment by gselander** [comment]
Implement proposal discussed in latest interim meeting.

**Comment by gselander** [comment]
I reopened this issue following the discussion of MTI cipher suite at the LAKE interim Jan 2021. 

Recap: Following the discussion above and at the LAKE interim Dec 2020 (minutes:
https://datatracker.ietf.org/meeting/interim-2020-lake-04/materials/minutes-interim-2020-lake-04-202012181600-00)
we formulated the following recommendation in EDHOC-04:

"To enable as much interoperability as we can
  reasonably achieve, less constrained devices SHOULD implement
  both cipher suite 0 (AES-CCM-16-64-128, SHA-256, X25519, 
  EdDSA, Ed25519, AES-CCM-16-64-128, SHA-256) 
  and cipher suite 2 (AES-CCM-16-64-128, SHA-256, P-256, 
  ES256, P-256, AES-CCM-16-64-128, SHA-256).
  Constrained endpoints SHOULD implement cipher suite 0 or cipher
  suite 2."

Please consider the arguments leading up to this formulation when proposing a change.

**Comment by malishav** [comment]
I would like to understand better the pitfalls of Option 1:

> This has negative consequences on performance and security, which will remain for long time.

Performanse-wise, the indicators we care about are:
a) processing time
b) code footprint
c) messaage overhead

In terms of (a), a software implementation of Ed25519 seems to be favored over ECDSA. From John's slides at [1], I gather that bad number of ECDSA have been due to unoptimized implementations of P-256 and that on some platforms ECDSA and Ed25519 have "equal performance". More importantly, the state-of-the-art constrained devices have dominantly ECDSA hardware accelerators. If we are to optimize for the constrained side, as we usually do, this indicator favors ECDSA. Since we are talking about hardware, this is expected to remain for at least the next 5-10 years, considering what is already deployed. 

In terms of (b), an implementation of Ed25519 requires SHA-512, in addition to SHA-256 that is needed by EDHOC, so two hash functions. Again, constrained devices have dominantly SHA-256 acceleration, without clear plans on adding SHA-512 to the mix. Code footprint favors ECDSA.

In terms of (c), there is no difference.

My conclusion from (a), (b) and (c) is that the argument on the negative impact of ECDSA on performance in constrained devices does not hold and that ECDSA is in fact favored performance-wise.

Security-wise, Ed25519 is favored. There have been speculations on the possible backdoors in the NIST P-256 curve. As far as I am aware, these are still considered speculations. The problem are the attacks on the signature algorithm, ECDSA. A notable example is Minerva [1], an implementation attack. What are the other attacks on ECDSA we should take into consideration? Do these attacks affect the hardware-accelerated implementations in constrained devices we are targeting?

[1] https://datatracker.ietf.org/meeting/interim-2020-lake-04/materials/slides-interim-2020-lake-04-sessa-edhoc-issues-after-03-00 (slide 15)
[2] https://minerva.crocs.fi.muni.cz

**Comment by gselander** [comment]
People may have missed that @emanjon provided input to this issue in 
https://mailarchive.ietf.org/arch/msg/lake/75nRaD6czYG6RqLT06Qe8C_lsaM/

@malishav:  Would you like to comment on this input, either here or on the mailing list? 
Can we narrow down the remaining concerns?

**Comment by malishav** [comment]
@gselander I think that @emanjon 's mail summarizes nicely the data points that we should take into account to make a decision. From that email, I concurred with his suggestion to delay the decision on this as late as possible, when other issues are closed. Should we have the consensus call at the IETF 111 meeting?

**Comment by emanjon** [comment]
Seems like there is agreement on this now. Closing.
