### ISSUE TITLE
Why it is required to send a list of cipher suites in message 1? Why it is not enough to send only the selected suite?

### ISSUE THREAD

**Issue by StefanHri** [lake-wg/edhoc#29]
In section 5.1.1.  Example Use of EDHOC Error Message with SUITES_R: 

* the Initiator sends SUITES_I = [5,5,6,7]. The selected suite is 5. 
* The responder supports only suite 6 -> the selected suite 5 is not supported 
* the responder sends error msg containing  SUITES_R = 6. 
* The information that suites 5,6,7 are supported by the initiator is not used ->

  Is it not enough to only send SUITES_I = 5?

  I know it is possible to truncate SUITES_I, but is it not better when the initiator sends the selected suite? Then if the responder does not support this suite it can answer with a list of suites?

**Comment by gselander** [comment]
Yes, it is enough to only send SUITES_I = 5, and the responder can answer with a list of suites. That is a different example, similar to the second example.

In the first example it is illustrated that the Initiator tells the Responder that it supports 5,6,7 and that it proposes to use 5. The initiator could in this case have sent just 5, that would have been a different example. Some of the illustrations intended with this example is to show a) that the Initiator can inform the Responder about suites it supports, b) that the Initiator can support more suites than it sends, and c) an example of the second message from the Initiator [6,5,6] which protects against downgrade attacks since it repeats all information about more preferred suites.

In the second example, the proposed suites by the Initiator are disjoint from those proposed by the Responder, which is addressing your second point. Again the suites of the first message are repeated in the second message and the selected is added. Given that the supported suites are the same in the first and second example, but the initiator is showing different suites in message_1 in the two examples, we thought it would be clear that yet other variants are possible, including only showing one suite, which would then be the selected suite. Can we make the examples more clear?

**Comment by StefanHri** [comment]
I am missing a top-level explanation of the procedure and its rationale. 
Which use cases we are trying to cover?

Why it is not enough to say: the initiator selects a cipher suite and sends it to the responder. The responder either accepts or sends its list. In the latter case, the initiator selects from the received list a new preferred suite.

**Comment by gselander** [comment]
@StefanHri You are right that the default procedure is that the Initiator sends the selected cipher suite. This example had the ambition to explain why things work also in corner cases, but your question made clear that we lost focus on the most common way how this should work. I have tried to fix that in caea215, have a look!

**Comment by StefanHri** [comment]
looks good for me.
