### ISSUE TITLE
Prepending 0x02 to the x coordinate to ECC public keys and clarity of Appendix B

### ISSUE THREAD

**Issue by StefanHri** [lake-wg/edhoc#321]
I and @stoprocent  were discussing if 0x02 should or should not be prepended to P256 public keys before they are used in EDHOC. 

Appendix B says: "For such use, the compact
   representation can be transformed into the SECG point compressed
   format by prepending it with the single byte 0x02 (i.e., M = 0x02 ||
   X)."

But section 3.7 says that only the x coordinate should be used (no 0x02). In addition, the traces [1] also does not have 0x02.

[1]: https://lake-wg.github.io/edhoc/traces-of-14/draft-ietf-lake-traces.html#name-message_1-second-time

**Comment by stoprocent** [comment]
As I was writing to @StefanHri, this was discussed before and I remember that it's clear that we are only using x without any prefixes.

**Comment by gselander** [comment]
Yes, this was discussed in #195. 

Section 3.7 says:
"The ephemeral public keys in EDHOC (G_X and G_Y) use compact representation ..."

 Appendix B says:
"This section defines a format for compact representation based on ..."

and later

"If a y-coordinate is required for validation or compatibility with APIs the value ~yp SHALL be set to zero. For such use, the compact representation can be transformed into the SECG point compressed format by prepending it with the single byte 0x02 (i.e., M = 0x02 || X)."

But, as is stated, the latter is not compact representation, it is a transformation of the compact representation. 

Since this is the second time we get the comment, maybe we should clarify something? If so, what?

**Comment by gselander** [comment]
@StefanHri Please look at the commit above if it is more clear now.

**Comment by gselander** [comment]
No comment so I assume current text is OK.
