### ISSUE TITLE
Denial-of-service mitigation by increasing size of message_1

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#348]
The Denial-of-Service text in EDHOC mentions Echo. Another way to mitigate Denial-of-service used by QUIC is to intentionally increase the size of message_1. Can be done by adding `? PAD_1` or by sending a dummy `EAD`. I think the document should at least mention the use of EAD_1 as a way to prevent Denial-of-Service.

**Comment by emanjon** [comment]
```
   message_1 = (
     METHOD : int,
     SUITES_I : suites,
     G_X : bstr,
     C_I : bstr / -24..23,
     ? EAD_1 : ead,
   )
```

Three alternatives to make message_1 bigger

1. Add `? PAD_1 `
2. Add a lot of suites to `SUITES_I`
3. Add a padding `EAD_1 `

**Comment by emanjon** [comment]
I think EAD_1 is a good way to go. I plan to make a PR discussing amplification and the solution of making message_1 bigger mentioning the EAD alternative.

**Comment by emanjon** [comment]
If a EAP padding type would be registered, it could be argueed that ? PAD_2, ? PAD_3, and ? PAD_4 is not needed.

```
   ead = 1* (
     ead_label : int,
     ead_value : bstr,
   )
```

Note that with EAD, padding is minimum 2 bytes. I.e., 1 byte padding is not possible.

**Comment by marco-tiloca-sics** [comment]
Just like for any other EAD items, if we use a new EAD_1 item for padding message_1, this item will also have to be handed off to "the application" for processing external to EDHOC, where it can be treated as padding and ignored.

In the other EDHOC messages, padding and its addition/removal does pertain to the core EDHOC message processing. That's why using PAD_1 can actually be better and more aligned with how padding is done already in other messages.

A good value for PAD_1 would be a sequence of CBOR simple value "true", like for the other PAD_X. A good position for it would be after C_I, i.e., before the EAD_1 field (if present).

**Comment by emanjon** [comment]
Thanks for the quick input Marco. Let's discuss at IETF 115. Göran pointed out that this issue might be related to #275

**Comment by gselander** [comment]
Unfortunately, we missed to discuss this in the LAKE meeting yesterday.

Anyone against having optional padding after C_1 in message_1?

Using the same encoding as for the other padding: PAD_1 = 1* true

**Comment by emanjon** [comment]
This would need some discussion.

- Adding `PAD_1 = 1* true` is a change to the wire format
- Addding a padding EAD seems like a perfect fit for Christians use case in #275.
- Having two ways to do padding is probably not optimal.
- As Marco points out, sending padding to the application is a bit strange. But would maybe be exactly what Christian is looking for.

Maybe we could have a meeting with all interested parties already during IETF 115?

**Comment by sftcd** [comment]
Hiya,

Maybe take this topic to the list?

Ta,
S.

**Comment by emanjon** [comment]
> Maybe take this topic to the list?

Yes, we have already agreed that this was missed yesterday and that we will take it to the list soon (today or tomorrow). We might have some offline discussions before so that we can summarize the issue better to the list.

**Comment by gselander** [comment]
An ad-hoc group at IETF 115  (Marco, Mališa, John and me) discussed this. We think this feature is well motivated and propose to add 

> PAD_1 = 1* true 

before ? EAD_1 at the end of message_1:
 
> ...
  C_I : bstr / -24..23,
  ? PAD_1 : 1* true,
  ? EAD_1 : ead,
)

While this is changing message_1 and thereby changing implementations, it is a minor optional feature only mandatory to support in the receiver, and no impact on current test vectors.

The alternative to use EAD instead is possible but not preferred since EAD belongs to the application. Even if we would reserve, say, ead_label 0 for this purpose, it means that EDHOC need to search for one among potentially several EAD items for this label, which we think is out of scope for EDHOC. Since #275 was closed it is not clear that additional support for that issue is really needed.

The proposed format using the CBOR simple type 'true' coincides with the definition of padding in the other messages, though here used for a different purpose (not to hide length of non-padding since message_1 is not encrypted).

The location of this field in message_1 was discussed and this proposal was considered least intrusive. There was resistance against having an optional field first, where there also is a potential confusion with the prepended 'true' marking message_1. Out of the two optional fields it was preferred to have this first since it is easy to discard if present.

It was a discussion about changing one of the uses of 'true' (prepended byte, padding) to another CBOR simple type, but with this location of PAD_1 there is no risk for confusion. (If you think that is worth doing, this is the moment to speak up!)

More input is welcome (even if it is just thumbs up).

**Comment by gselander** [comment]
Note that the normative statements about padding extends to message_1, but I propose to remove "of plaintext" to emphasize the change. Although message_1 is not encrypted, the term PLAINTEXT is only used in the encrypted messages message_2, message_3, message_4.

OLD
Implementations MAY support padding of plaintext when sending messages. Implementations MUST support padding of plaintext when receiving messages, i.e., MUST be able to parse padded messages.

NEW
Implementations MAY support padding when sending messages. Implementations MUST support padding when receiving messages, i.e., MUST be able to parse padded messages.

(The change is already made in PR #357.)

**Comment by chrysn** [comment]
I don't quite understand the rationale of doing this as an extra thing in the protocol rather than using the perfectly viable EAD1 path (which, by the way, works already, thanks to must-understand and optional numbers).

The distinction between "belongs to the application" and "is part of the protocol" sounds rather arbitrary to me, given that by the allocated numbers EADs support composition. Just the way options work in CoAP. Creating a smooth path for amplification mitigation may be implemented as part of the EDHOC library, or (if the EDHOC library is completely unaware of where the EDHOC messages are sent through, which conceptually it can) as part of the application (which is the authority on what is actually needed), or as part of some middleware that glues the two together; that's the beauty of composability.

I think that addresing this in EAD would be the better choice. (Especially given that it'd be beneficial to have a (or some) "grease" EAD option(s) around in the style of [RFC8701](https://www.rfc-editor.org/rfc/rfc8701), and these could just as well share code points).

**Comment by emanjon** [comment]
I agree with Christian. My preference would be to do this with EAD and remove PAD.

**Comment by marco-tiloca-sics** [comment]
Although I tend to see the PAD_1 approach simpler and more intuitive, using an EAD item is also just fine.

Admittedly, I wasn't thinking of the greasing aspect (thanks, @chrysn !), or to mandate support for EAD items altogether (like [1] does, together with consistently applying the same padding approach to all the EDHOC non-error messages).

So let's go for EAD-based padding then :-) Isn't it good to just go for ead_label 0?


[1] https://github.com/lake-wg/edhoc/pull/360/files

**Comment by gselander** [comment]
So we have changed this back and forth a couple of times. What convinced me about using EAD for padding was that it is ultimately the application of EDHOC that is in control of EAD_x (which are critical to determine the amplification factor and length of PLAINTEXT_x) and thus can determine the necessary padding in messages 1 to 4. So it might just as well produce the padding itself (in EAD_x) rather than asking EDHOC to do it, which complicates EDHOC and the call.

**Comment by gselander** [comment]
PR #360 is merged
