### ISSUE TITLE
WGLC comment from Christian Amsüss

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#353]
https://mailarchive.ietf.org/arch/msg/lake/D-THUR-raS57JEfZjKFsMqFHl4M/

There is one minor piece of text I suggested at [141] that I think might
help EAD specifiers (who might not know that "we don't look into EDHOC
internals and key material, and the data we reveal is revealed by
design, so we're good" can be sufficient security analysis), but that's
merely a minor suggestion at this point.

Best regards
Christian

[141]: https://github.com/lake-wg/edhoc/issues/141#issuecomment-1081500628

**Comment by gselander** [comment]
I'm not sure it is possible to give sufficient high-level criteria that new EAD items are not causing substantial damage. This is one reason why there are several caveats in the draft about using EAD, and why new EAD items are "specification required".

We already state that EAD fields should be considered unprotected by EDHOC, so that should be expected. The application should anyway not have access to secret internal keys of EDHOC, so I'm not sure that is necessary to state. The re-use of an EDHOC ephemeral key for other Diffie-Hellman operations is already done in EDHOC and lake-authz. 

We may consider adding some non-complete guidance if that helps, but each new EAD specification needs to be reviewed, and I'm not sure there is any way around that.

Other opinions?

**Comment by emanjon** [comment]
I don't see how we would be able to write something perfect here. I think it needs to be up to the specification of the EAD item

**Comment by gselander** [comment]
Closing this now. We can re-open if there are further comments.
