### ISSUE TITLE
Add guidelines for distinguishing received messages. Relates to #30.

### ISSUE THREAD

**Issue by marco-tiloca-sics** [lake-wg/edhoc#39]

**Comment by gselander** [comment]
Proxying draft solution:

    First, check if it is an Error Message. That's the case if and only
    if the first or second element of the sequence is a text string.

    If it's not an Error Message:

    - If the sequence has 1 or 2 elements, it's Message 3.

    - If the sequence has 3 elements, it's Message 2.

    - If the sequence has 5 elements, it's message 1.

    - If the sequence has 4 elements, check its second element.
    --- If it is an array or an integer, it's Message 1.
    --- If it is a byte string, it's Message 2.

**Comment by marco-tiloca-sics** [comment]
Since both a client and a server can act as Initiator or Responder, this early understanding helps in taking the next steps when receiving a message.

This helps especially for retrieving the status of an ongoing EDHOC execution when receiving Error Message, Message 2 or Message 3, or for starting processing Message 1 that potentially yields the creation and storage of a new execution status as Responder.

For the status retrieval, the endpoint uses C_I/C_R (if included in the message) or implicit transport protocol indications, depending on the correlation method.

**Comment by emanjon** [comment]
I think these are good points, but I don't see exactly why you are having a problem and how the draft should be updated. Could you provide a conrete message flow that also shows which protocol layers that are used below EDHOC. Could be that normative text on how to distinguish the messages are needed, or this is mostly implementation guidance. Might also be that something in the draft needed to be more strict or change. I think both endpoints sending message_1 has not been discussed other than from a security perspective.

**Comment by marco-tiloca-sics** [comment]
It is just for implementation guidance, as a possible way to do the message distinction. I didn't think of something to add or fix in the actual protocol.

**Comment by chrysn** [comment]
I'd prefer not to parse the full message (which, given it's CBOR sequences, ) at the point where I branch around; looking at the decision tree from that side.

I'm only considering a server's situation here, so it can receive a Message 1, a Message 3 (carrying a c_r, of the server's choice), or a Message 2 or 4 (both carrying a c_i, with a value of the server's choice).

Such a server WOULD PROBABLY pick c_i and c_r values which it can distinguish from each other (say, by their least significant bit, or by a prefix), and WOULD PROBABLY NOT pick any value that's a legal METHOD_CORR (ie. no values from 0 to 15 inclusive).

The server can then tell whether it's
* Message 1: first element in 0..=15
* Message 3: first element is a C_R
* Message 2: first element is a C_I
* Message 4: does that ever get used with a server at all?

  Probably not, as "In deployments where no protected application message is sent from the Responder to the Initiator" is not the case -- because that's one of the cases where it is not needed.

  If s, the distinction between message 2 and 4 is "is it over after having decoded the two elements" (given message 4 has 2 elements in presence of a C_I, message 2 has 4).

**Comment by gselander** [comment]
Provided by transport. In -08 this is described for CoAP in Appendix A.3.
