### ISSUE TITLE
Missing Responder private key in test vector.

### ISSUE THREAD

**Issue by TimothyClaeys** [lake-wg/edhoc#42]
In the following test vector [method 2 - Static(Initiator)-Sign(Responder)]:

https://github.com/lake-wg/edhoc/blob/c73dc6affe2d7a47fa8eac97be4d4bbd8bd7c667/test-vectors/vectors.txt#L978

The Responder is missing its private authentication key. The Responder's private key is required to compute the `sign_or_mac2 `part of `message 2`, using an COSE_Sign1 structure.

**Comment by fpalombini** [comment]
Again due to the copy paste typo in the generation code, now fixed in a09570b. Need to run the code to regenerate new test vectors using the updated code, I wouldn't update the appendix at the same time to match the vectors.txt though, because that's not really necessary (they are still correct, just need to fix the print).

**Comment by emanjon** [comment]
Fixed in test-vector-05
