### ISSUE TITLE
Clarify assumptions regarding use of TEE

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#5]
Extracted from https://arxiv.org/abs/2007.11427
https://www.ietf.org/proceedings/108/slides/slides-108-lake-tamarin-study-of-edhoc-00

OPTLS takes advantage of the use of TEE, relevant for STAT-based methods.

**Comment by gselander** [comment]
This doesn't have to be TEE required or not required. The protocol could offer some security properties for non-TEE implementations, but provide better properties with certain use of TEE.

**Comment by emanjon** [comment]
Recent update provide recommendation to store as much as possible and to provide as many operations as possible in TEE.

**Comment by gselander** [comment]
More input about TEE would be good. 
Stefan Hristozov: How much state can we store in TEE of microcontrollers? What protocol components can we assume to implement in the TEE? How is this expected to change in the future?

**Comment by pbtgit** [comment]
Hello Göran,

My limited experience of TEE is ARM TZ on ARM V8 and there the execution state can be  stored (protected with using device unique keys) to NV to allow power save of SDRAM.

I am not aware of exactly how this is differs on micro controllers since  ARM V8-M.
But it seems like mbedTLS is used by several projects including TF-M which is “Trusted FW for ARM V8-M”.


Best regards
Peter

**Comment by StefanHri** [comment]
To save state in the secure world RAM of a Cortex M23/33 is not a problem at all. On those microcontrollers, the total available RAM can be divided between the secure and non-secure worlds. In our work we save all intermediate secret results of the computations (the state) in the secure world, which was a few hundred bytes. 
@gselander, @emanjon: Can you post a link to the  OPTLS with TEE document?

**Comment by gselander** [comment]
@StefanHri The formulation of this issue is based on the comment from formal verification work referenced a the top. The OPTLS paper is here: 

https://eprint.iacr.org/2015/978.pdf

But this paper does not formulate properties in terms of TEE. As I understand the reasoning, there is a long term private key ('s'), potentially in security storage/execution, and an ephemeral private keys ('x') which may not be in secure storage/execution. By construction these keys are used together to derive the session key. Hence neither compromise of long-term key only nor ephemeral secret only reveals the session key.

**Comment by StefanHri** [comment]
Are we talking about the static DH key authentication modes, or authentication with signatures, or both?

**Comment by gselander** [comment]
The comment was specifically about static DH based authentication. The general distinction between long term and ephemeral of course still applies to signature based AKE, but I'm not aware of an analogue in properties of derived keys.

**Comment by emanjon** [comment]
While the original comment was specifically about static DH based authentication. I don’t think there is anything specific with static DH at all. The question is what parts we can expect to be implemented in a TEE. Key storage? Crypto operations like ECDH, SIGN, HMAC? The whole EDHOC protocol? EDHOC and OCSORE?

**Comment by gselander** [comment]
Trimmed the email header and trailer from the previous comment (which I don't disagree with - I responded specifically in the context OPTLS).

**Comment by StefanHri** [comment]
The idea of a TEE is to put as little as possible code in the TEE in order to minimize the chance that exploitable vulnerabilities are introduced in the secure-world. 

" The question is what parts we can expect to be implemented in a TEE?"
I will say it depends on the specific application/IoT device how much benefit is drawn (or must be drowned) through using the TEE. For some huge applications, it may be OK to put the complete OSCORE and EDHOC implementation in the TEE. For others however which have to be highly secure, it is better to put only the crypto operations and the keys in TEE.

 In our paper (still not published. When it gets published I will put a reference here) we are considering the latter case. Here is the subsection about sensitive assets:
 
 "Sensitive Assets. By analyzing the EDHOC specifica-
tion we identified the following key material as sensitive: 1)
the long term authentication keys, i.e. secret signature keys
or secret static DH keys, 2) the public authentication key of
the other party when RPK is used and the root public key of
the CA when certificates are used, 3) intermediate EDHOC
keys and 4) the result of the EDHOC protocol. An attacker
having access to one of those keys may: 1) impersonate the
device by leaking its long term authentication keys, 2) fool
the device that its talking to a legit peer by changing the
peer’s public key or the root public key of the CA and 3) com-
promise the security of EDHOC by leaking or manipulating
its intermediate keys or the end result of the protocol.
Also sensitive are all cryptographic routines using the
keys. If these routines are manipulated, they may leak the
keys or allow the EDHOC protocol to succeed although the
communication peer is not authentic."
 
 
 I think letting the ephemeral secret key outside the TEE is not a good idea because in this way an attacker outside the TEE may calculate the derived key.

**Comment by pbtgit** [comment]
I agree with above. It may be possible to put EDHOC/OSCORE in a TEE but as pointed out above the sensitive assets are the keys.
The concern of protecting EDHOC/OSCORE code can be addressed using some form of "secure boot", memory protection etc.

**Comment by emanjon** [comment]
I updated the security considerations based on the discussion here. Removed that EDHOC is optimally implemented in TEE and added "secure boot".

Note that Key compromise is described in one part of sec con and TEE in another.

I think this can be closed
