### ISSUE TITLE
Clarify properties inferred from other crypto

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#6]
Extracted from https://arxiv.org/abs/2007.11427
https://www.ietf.org/proceedings/108/slides/slides-108-lake-tamarin-study-of-edhoc-00

"Unclear if there is an *exact* mapping to Noise, so proofs of those does not necessarily automatically carry over."

Similar, if relevant, for OPTLS.

Update security claims accordingly. In particular, the section on security properties in the security considerations is not making clear what methods the properties apply to.

**Comment by emanjon** [comment]
The security consideration has been updated several times since 2007. In particular is has been updated to clearly refer to method when something only is true for a specific method.

The is not a direct mapping to OPTLS, the might be a mapping to Noise, but this has not been anylysed and is not used. The is strict mapping to SIGMA for the signature case, at least when a subject name is used.

I close this now. It can be reopened if there are more concrete and recent things that need to be updated.
