### ISSUE TITLE
Strange places to mention draft-palombini-core-oscore-edhoc

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#72]
draft-palombini-core-oscore-edhoc is mention several times in general places it should maybe not be mentioned.

draft-palombini-core-oscore-edhoc is not mention in 
7.2.  Transferring EDHOC in CoAP
where it should absolutly be mentioned.

**Comment by gselander** [comment]
draft-palombini-core-oscore-edhoc (now draft-ietf-core-oscore-edhoc) is now only mentioned in 7.2.2, so the issue is seemingly resolved.

But we probably want to make more changes here. draft-ietf-core-oscore-edhoc is already mentioning combined use of OSCORE and EDHOC, so we may want to move section 7.2.1. "Deriving an OSCORE Context from EDHOC" and the last part of section 7.2.2 to that draft.

In which case we would want to keep a reference of draft-ietf-core-oscore-edhoc in 7.2.0.

(Note also changes proposed in 7.2.2: #91 )
