### ISSUE TITLE
JSON test vector format for automatic parsing

### ISSUE THREAD

**Issue by emanjon** [lake-wg/edhoc#78]
We have gotten feedback that the test vectors should be in JSON intead (or in addition) of a text file. I plan to fix this.

**Comment by TimothyClaeys** [comment]
+1

I think this would make it a lot easier to create unit tests for the implementations.

I've provided an example how I have structured the test vectors in JSON format.

https://github.com/TimothyClaeys/EDHOC-C/blob/master/test/test_vectors/vector1.json

**Comment by gselander** [comment]
Thanks @TimothyClaeys !

Comments on the proposal are welcome!

In the interest of increasing the number of test vectors we should also set up how people can input their results using this template, when we have agreed on it. 

For that we also need to have a well defined input in JSON, any proposal?

**Comment by marco-tiloca-sics** [comment]
Thanks for this, it looks good!

As a general comment, I would have to produce new output for several sub-elements and in this particular format (which is fine).

More specific comments:

* To fully cover the considered configuration, 'auth_key' in the "I" and "R" objects should also include the string to use as subject name when building CRED_x.

* 'secret' can be better renamed to 'g_xy'.

* Why including 'p_2m' and 'p_3m' in the "S" object? They are always the empty byte string.

* As to 'a_2m', 'a_3m' and 'a_3ae in the "S" object, they are available for me to print only deep in the COSE library I use, so not really in my actual implementation. That's why now I'm easily printing only the actual external data (i.e. << TH_2, CRED_R, ? AD_2 >>, << TH_3, CRED_I, ? AD_3 >> and  << TH_3, CRED_I, ? AD_3 >>). So, I would have to manually (re-)build the AAD array just for printing it, considering also the "Encrypt0" context string and << ID_CRED_X >>.

* The "S" object may include the further elements related to message_4 when this is used.

**Comment by gselander** [comment]
Do we need to compile somewhere the CBOR used to create this data? For example, that "eph_key" = {1: 1, -1: 4, -2: h' ... ', -4: h' ... '} in this case?

(Section 3.5 already says:
"The ECDH ephemeral public keys are formatted as a COSE_Key of type EC2 or OKP according to Sections 7.1 and 7.2 of [I-D.ietf-cose-rfc8152bis-algs] " but may not be obvious on first encounter with the test vector.)

**Comment by emanjon** [comment]
I very quickly transformed my -10 test vectors to JSON (or almost JSON as JSON forbids a trailing comma.....)

https://github.com/lake-wg/edhoc/tree/master/test-vectors-10-json

I just quickly tried to convert my test vecors to JSON. I tried to somewhat align with Timothy, but there might be differences. In my test vectors, names ending with _raw and not CBOR and everything else are CBOR sequences.

Happy to change my JSON test vectors to any format implementors would want.

**Comment by emanjon** [comment]
I merged my two cpp files. JSON can now be found in

https://github.com/lake-wg/edhoc/tree/master/test-vectors-10

@TimothyClaeys and @marco-tiloca-sics if you agree on a JSON format, I'll update my output to match that. I don't have any opinions about the JSON format. Now I just made something very quick that aligned with the draft out that is used in the draft.

**Comment by TimothyClaeys** [comment]
Hi @emanjon,

I think this looks good. Maybe a small remark: for automatic parsing purposes, I might be useful to put each test case in a parent JSON structure. Something like this:

`
{
    "test_vector_1": {
        "method": 0,
        "suites_i": "00",
        ...
     },
     "test_vector_2": {
        "method": 1,
        "suites_i": "01",
        ...
      }
}
`

**Comment by marco-tiloca-sics** [comment]
Looks good to me too; I agree with Timothy's point.

**Comment by emanjon** [comment]
Hi, I added a parent map as suggested by Timothy. I also removed the extra commas to make the output correct JSON.

**Comment by emanjon** [comment]
If we are happy enough the current format, I plan to close this issue soon. Any future changes can be discussed in the general #47 or in new issues.
